port: 8080
# tls_key: cmd/go-graphkb/keys/server.key
# tls_cert: cmd/go-graphkb/keys/server.crt

mariadb:
  username: graphkb
  password: password
  host: db
  database: graphkb

sources:
  csv-employees: token_auth_for_csv_importer
